# Generated by Django 5.1.1 on 2024-09-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pjtimeline',
            table='pjtimeline',
        ),
        migrations.AlterModelTable(
            name='portfolioboard',
            table='portfolioboard',
        ),
        migrations.AlterModelTable(
            name='portfoliofiles',
            table='portfoliofiles',
        ),
        migrations.AlterModelTable(
            name='qna',
            table='qna',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='userinfo',
        ),
    ]
