# Generated by Django 5.1.1 on 2024-09-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pjtimeline_table_alter_portfolioboard_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pjtimeline',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='참여 역할'),
        ),
    ]
