# Generated by Django 5.1.1 on 2024-09-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pjtimeline_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='pjtimeline',
            name='order_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='발주처'),
        ),
    ]
