# Generated by Django 5.1.1 on 2024-09-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pjtimeline_order_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioboard',
            name='board_write',
        ),
        migrations.RemoveField(
            model_name='portfolioboard',
            name='user',
        ),
        migrations.RemoveField(
            model_name='portfolioboard',
            name='user_name',
        ),
        migrations.AddField(
            model_name='portfolioboard',
            name='board_semidesc',
            field=models.TextField(blank=True, null=True, verbose_name='글 요약 내용'),
        ),
        migrations.AddField(
            model_name='portfolioboard',
            name='order_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='표시 순서'),
        ),
        migrations.AddField(
            model_name='portfolioboard',
            name='pf_date',
            field=models.DateField(blank=True, null=True, verbose_name='프로젝트 일자'),
        ),
        migrations.AddField(
            model_name='portfolioboard',
            name='pf_link',
            field=models.TextField(blank=True, null=True, verbose_name='프로젝트 링크'),
        ),
        migrations.AlterField(
            model_name='portfolioboard',
            name='board_desc',
            field=models.TextField(blank=True, null=True, verbose_name='글 전체 내용'),
        ),
    ]
