# Generated by Django 5.1.1 on 2024-09-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_portfolioboard_board_write_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_addr1',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_addr2',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_corptype',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_tel1',
        ),
    ]
