# Generated by Django 5.1.1 on 2024-09-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_userinfo_user_addr1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
