# Generated by Django 5.1.1 on 2024-09-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_pjtimeline_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioboard',
            name='pf_type',
            field=models.CharField(choices=[('AI', 'AI'), ('ENTERPRISE', '기획'), ('WEB_DEV', '웹 개발')], default='AI', max_length=20, verbose_name='포트폴리오 유형'),
        ),
    ]
