# Generated by Django 5.1.1 on 2024-09-16 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_portfolioboard_pf_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioboard',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL),
        ),
    ]
