# Generated by Django 5.1.1 on 2024-09-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_portfolioboard_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioboard',
            old_name='user_id',
            new_name='user',
        ),
    ]
