# Generated by Django 5.1.1 on 2024-09-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_user_id_portfolioboard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioboard',
            name='pf_type',
            field=models.CharField(choices=[('AI', 'AI'), ('Planning', '기획'), ('WEB_DEV', '웹 개발')], default='AI', max_length=20, verbose_name='포트폴리오 유형'),
        ),
    ]
