# Generated by Django 5.1.1 on 2024-09-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_portfolioboard_pf_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioboard',
            name='board_desc',
        ),
        migrations.RemoveField(
            model_name='portfolioboard',
            name='pf_date',
        ),
        migrations.AddField(
            model_name='portfolioboard',
            name='desc_info',
            field=models.TextField(null=True, verbose_name='프로젝트 소개'),
        ),
        migrations.AddField(
            model_name='portfolioboard',
            name='desc_results',
            field=models.TextField(null=True, verbose_name='결과'),
        ),
        migrations.AddField(
            model_name='portfolioboard',
            name='desc_role',
            field=models.TextField(null=True, verbose_name='역할'),
        ),
        migrations.AddField(
            model_name='portfolioboard',
            name='desc_tasks',
            field=models.TextField(null=True, verbose_name='주요 작업 내역'),
        ),
        migrations.AddField(
            model_name='portfolioboard',
            name='pf_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='프로젝트 종료일'),
        ),
        migrations.AddField(
            model_name='portfolioboard',
            name='pf_start_date',
            field=models.DateField(null=True, verbose_name='프로젝트 시작일'),
        ),
        migrations.AlterField(
            model_name='portfolioboard',
            name='board_semidesc',
            field=models.TextField(null=True, verbose_name='프로젝트 간단 설명'),
        ),
        migrations.AlterField(
            model_name='portfolioboard',
            name='board_title',
            field=models.CharField(max_length=200, null=True, verbose_name='프로젝트 제목'),
        ),
        migrations.AlterField(
            model_name='portfolioboard',
            name='pf_link',
            field=models.URLField(blank=True, null=True, verbose_name='프로젝트 링크'),
        ),
        migrations.AlterField(
            model_name='portfolioboard',
            name='pf_type',
            field=models.CharField(choices=[('AI', 'AI'), ('ENTERPRISE', '기획'), ('WEB_DEV', '웹 개발')], default='AI', max_length=20, verbose_name='포트폴리오 유형'),
        ),
    ]
