# Generated by Django 5.1.1 on 2024-09-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_portfolioboard_board_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioboard',
            name='pf_type',
            field=models.CharField(choices=[('AI', 'AI'), ('Planning', '기획'), ('WEB_DEV', '웹 개발')], default='AI', max_length=20, verbose_name='포트폴리오 유형'),
        ),
    ]
