# Generated by Django 5.1.1 on 2024-09-29 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_portfolioboard_pf_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliofiles',
            name='file_path',
        ),
        migrations.AddField(
            model_name='portfoliofiles',
            name='file_content',
            field=models.TextField(blank=True, null=True, verbose_name='추출된 파일 내용'),
        ),
        migrations.AddField(
            model_name='portfoliofiles',
            name='file_identifier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='파일 식별자'),
        ),
        migrations.AlterField(
            model_name='portfoliofiles',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='파일 업로드 일시'),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chatsession',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_user', models.BooleanField()),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chatsession')),
            ],
            options={
                'db_table': 'chatmessage',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_pf_types', models.CharField(max_length=100)),
                ('pref_tech', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userpreference',
            },
        ),
        migrations.CreateModel(
            name='PortfolioKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('frequency', models.IntegerField(default=1)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='api.portfolioboard')),
            ],
            options={
                'db_table': 'portfoliokeyword',
                'unique_together': {('portfolio', 'keyword')},
            },
        ),
    ]
