# Generated by Django 5.1.1 on 2024-10-08 01:55

from django.db import migrations, models

def set_default_session_key(apps, schema_editor):
    ChatSession = apps.get_model('api', 'ChatSession')
    for session in ChatSession.objects.all():
        if not session.session_key:
            session.session_key = session.session_id or f"anonymous_{session.id}"
        session.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_chatmessage_session_chatmessage_session_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsession',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='session_key',
            field=models.CharField(max_length=40, unique=True, null=True),
        ),
        migrations.RunPython(set_default_session_key),
        migrations.AlterField(
            model_name='chatsession',
            name='session_key',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='session_id',
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user'], name='api_chatses_user_id_f0a24c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['session_key'], name='api_chatses_session_a46459_idx'),
        ),
        migrations.AlterModelTable(
            name='chatsession',
            table=None,
        ),
    ]