# Generated by Django 5.1.1 on 2024-10-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_user_id_chatsession_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='gpt_message',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user_message',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='last_interaction',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
