# Generated by Django 5.1.1 on 2024-10-08 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_chatmessage_gpt_message_and_more'),
    ]

    operations = [
    ]
