# Generated by Django 5.1.1 on 2024-10-08 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20241008_1235'),
    ]

    operations = [
    ]
