# Generated by Django 5.1.1 on 2024-10-09 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20241008_1258'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chatmessage_user_id_27a1be_idx',
            old_name='api_chatmes_user_id_ee15fd_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chatmessage_session_0856b6_idx',
            old_name='api_chatmes_session_fe703c_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='chatsession_user_id_41e224_idx',
            old_name='api_chatses_user_id_f0a24c_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='chatsession_session_f5bbdb_idx',
            old_name='api_chatses_session_a46459_idx',
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table='chatmessage',
        ),
        migrations.AlterModelTable(
            name='chatsession',
            table='chatsession',
        ),
    ]
