# Generated by Django 5.1.1 on 2024-10-09 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_chatmessage_gpt_message_chatmessage_user_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
